/** @type {import('stylelint').Config} */
export default {
    extends: ["stylelint-config-standard-scss"],
    plugins: ["stylelint-plugin-logical-css", "stylelint-scss"],
    rules: {
        "at-rule-no-unknown": null,
        "scss/at-rule-no-unknown": [true, {
            "ignoreAtRules": [
                "function",
                "mixin",
                "include",
                "extend",
                "use",
                "forward",
                "return",
                "if",
                "else",
                "for",
                "each",
                "while",
                "warn",
                "debug",
                "error",
                "layer",
                "property"
            ],
            "severity": "warning"
        }],
        "function-no-unknown": null,
        "scss/function-no-unknown": [true, {
            "ignoreFunctions": [
                "color-mix",
                "oklch",
                "oklab",
                "style",
                "config",
                "emoji-to-icon",
                "md3-color",
                "md3-color-scheme"
            ],
            "severity": "warning"
        }],
        "keyframes-name-pattern": null,
        "at-rule-empty-line-before": ["always", { "severity": "warning", "except": ["first-nested", "blockless-after-blockless"] }],
        "max-nesting-depth": [6, { "severity": "warning" }],
        "selector-max-compound-selectors": [6, { "severity": "warning" }],
        "declaration-block-no-duplicate-properties": [true, { "severity": "warning" }],
        "scss/comment-no-empty": [true, { "severity": "warning" }],
        "selector-type-no-unknown": null,
        "block-no-empty": [true, { "severity": "warning" }],
        "comment-no-empty": [true, { "severity": "warning" }],
        "no-descending-specificity": null,
        "selector-class-pattern": null,
        "color-function-notation": ["modern", {"severity": "warning"}],
        "alpha-value-notation": ["percentage", {"severity": "warning"}],
        "custom-property-empty-line-before": null,
        "declaration-empty-line-before": null,
        "value-keyword-case": ["lower", { "severity": "warning", "camelCaseSvgKeywords": true }],
        "color-hex-length": ["short", { "severity": "warning" }],
        "unit-allowed-list": [
            "em", "rem", "s", "ms", "px", "%",
            "dvi", "dvb", "dvh", "dvw", "svh", "svw",
            "lvh", "lvw", "cqi", "cqb", "cqw", "cqh",
            "deg", "rad", "grad", "turn", "fr",
            "vh", "vw", "vmin", "vmax", "cqmin", "cqmax",
            "cm", "xl", "xs", "ch", "dvmin", "dvmax", "lvmin", "lvmax", "vb", "pt", "in", "hz"
        ],
        "scss/at-extend-no-missing-placeholder": null,
        "scss/selector-no-redundant-nesting-selector": null,
        "scss/selector-no-union-class-name": null,
        "scss/no-global-function-names": null,
        "scss/dollar-variable-pattern": null,
        "scss/dollar-variable-empty-line-before": null,
        "font-family-name-quotes": null,
        "property-no-deprecated": null,
        "declaration-property-value-keyword-no-deprecated": null,
        "length-zero-no-unit": null,
        "declaration-block-no-redundant-longhand-properties": null,
        "color-function-alias-notation": null,
        "selector-not-notation": null,
        "property-no-vendor-prefix": null,
        "rule-empty-line-before": null,
        "declaration-block-no-shorthand-property-overrides": null,
        "hue-degree-notation": null,
        "scss/at-if-no-null": null,
        "lightness-notation": null,
        "scss/at-mixin-argumentless-call-parentheses": null,
        "block-no-redundant-nested-style-rules": null,
        "property-no-unknown": [true, { "ignoreProperties": ["user-drag", "-webkit-user-drag"] }],
        "media-feature-range-notation": null,
        "custom-property-pattern": null,
        "declaration-block-single-line-max-declarations": null,
        "scss/double-slash-comment-whitespace-inside": null,
        "comment-empty-line-before": null,
        "comment-whitespace-inside": null,
        "scss/operator-no-unspaced": null,
        "scss/at-else-empty-line-before": null,
        "scss/operator-no-newline-after": null,
        "no-invalid-position-declaration": null,
        "scss/double-slash-comment-empty-line-before": null,
        "scss/at-else-closing-brace-newline-after": null,
        "scss/at-else-closing-brace-space-after": null,
        "scss/at-if-closing-brace-newline-after": null,
        "scss/at-if-closing-brace-space-after": null,
        "nesting-selector-no-missing-scoping-root": null,
        "scss/dollar-variable-colon-space-after": null,
        "scss/load-no-partial-leading-underscore": null,
        "syntax-string-no-invalid": null,
        "length-zero-no-unit": null,
        "block-no-redundant-nested-style-rules": null,
        "rule-empty-line-before": null,
        "property-no-deprecated": null,
        "property-no-vendor-prefix": null,
        "no-empty-source": null,
        "container-name-pattern": null,
        "shorthand-property-no-redundant-values": null,
        "scss/dollar-variable-colon-space-before": null,
        "media-feature-name-no-unknown": null,
        "scss/load-partial-extension": null,
        "font-family-no-duplicate-names": null,
        "selector-id-pattern": null,
        "scss/at-mixin-parentheses-space-before": null,
        "scss/at-function-parentheses-space-before": null,
        "selector-pseudo-class-no-unknown": null,
        "font-family-no-missing-generic-family-keyword": null,
        "declaration-block-no-duplicate-custom-properties": null,
        "scss/at-rule-conditional-no-parentheses": null,
        "scss/at-mixin-pattern": null,
        "scss/at-function-pattern": null,
        "import-notation": null,
        "logical-css/require-logical-properties": [true, {"severity": "warning"}],
        "logical-css/require-logical-units": [true, {"severity": "warning"}],
        "logical-css/require-logical-keywords": [true, {"severity": "warning"}]
    },
    overrides: [
        {
            files: ["**/shared/fest/veela/scss/**/*.scss", "**/fest/veela/scss/**/*.scss"],
            rules: {
                "value-keyword-case": null,
                "color-hex-length": null,
                "color-function-notation": null,
                "alpha-value-notation": null
            }
        }
    ]
}
